In [2]:
import camelot
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import os

In [4]:
tables = camelot.read_pdf('statements/statement_3.pdf', flavor='stream', pages='all')
print(tables[0])

c:\Users\rutsm\anaconda3\envs\dele_env\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")

<Table shape=(8, 1)>

c:\Users\rutsm\anaconda3\envs\dele_env\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 2
  warnings.warn(f"No tables found in table area {table_idx + 1}")

In [6]:
tables[1].df

,0,1,2,3,4
0,Deposits,,,,
1,ePOSBkids Account,,,,Account No. 407-46105-3
2,Date,Description,Withdrawal (-),Deposit (+),Balance (SGD)
3,,Balance Brought Forward,,,70.27
4,31/12/2022,FAST Payment / Receipt,8.00,,62.27
5,,PAYNOW TRANSFER,,,
6,,TO: ASON ANG,,,
7,,PAYNOW TRANSFER,,,
8,,OTHER,,,
9,02/01/2023,Funds Transfer,,80.00,142.27
10,,009-1-024105 : I-BANK,,,
11,02/01/2023,Funds Transfer,,68.00,210.27
12,,126-17874-3 : I-BANK,,,
13,02/01/2023,FAST Payment / Receipt,,35.61,245.88
14,,INCOMING PAYNOW REF 7101410,,,
15,,FROM: KLAUDINE SHANNON QUEK,,,
16,,PAYNOW TRANSFER,,,
17,,OTHER,,,
18,03/01/2023,FAST Payment / Receipt,42.00,,203.88
19,,PAYNOW TRANSFER,,,
20,,TO: YAN,,,
21,,PAYNOW TRANSFER,,,
22,,OTHER,,,
23,03/01/2023,FAST Payment / Receipt,2.93,,200.95
24,,PAYNOW TRANSFER,,,
25,,TO: KLAUDINE,,,
26,,PAYNOW TRANSFER,,,
27,,OTHER,,,
28,04/01/2023,Debit Card Transaction,16.40,,184.55
29,,CHATRAMUE SINGAPORE SI NG 31DEC,,,
30,,4628-4500-0420-5358,,,
31,04/01/2023,FAST Payment / Receipt,4.50,,180.05
32,,PAYNOW TRANSFER,,,
33,,TO: GURU NICE PTE.LTD.,,,
34,,NA,,,
35,,OTHER,,,
36,04/01/2023,FAST Payment / Receipt,32.00,,148.05
37,,PAYNOW TRANSFER,,,
38,,TO: MAYZEL TAN,,,
39,,PAYNOW TRANSFER,,,
40,,OTHER,,,
41,04/01/2023,FAST Payment / Receipt,13.19,,134.86
42,,PAYNOW TRANSFER,,,
43,,TO: SJIAYIN,,,
44,,PAYNOW TRANSFER,,,
45,,OTHER,,,
46,,Balance Carried Forward,,,134.86